In [51]:
import pandas as pd

In [52]:
# Cargar datos
csv_path = "../../data/processed/btc_silver.csv"
btc = pd.read_csv(csv_path)

In [53]:
btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1558 non-null   object
 1   Close         1558 non-null   float64
 2   High          1558 non-null   float64
 3   Low           1558 non-null   float64
 4   Open          1558 non-null   float64
 5   Volume        1558 non-null   int64
 6   daily_return  1558 non-null   float64
 7   day_of_week   1558 non-null   int64
dtypes: float64(5), int64(2), object(1)
memory usage: 97.5+ KB

In [54]:
btc['Date'] = pd.to_datetime(btc['Date'])

In [55]:
btc.set_index('Date', inplace=True)

In [56]:
btc

,Close,High,Low,Open,Volume,daily_return,day_of_week
Date,,,,,,,
2020-12-25,24664.791016,24710.101562,23463.673828,23733.570312,42068395846,0.039132,4
2020-12-26,26437.037109,26718.070312,24522.689453,24677.015625,48332647295,0.071853,5
2020-12-27,26272.294922,28288.839844,25922.769531,26439.373047,66479895605,-0.006231,6
2020-12-28,27084.808594,27389.111328,26207.640625,26280.822266,49056742893,0.030927,0
2020-12-29,27362.437500,27370.720703,25987.298828,27081.810547,45265946774,0.010250,1
...,...,...,...,...,...,...,...
2025-04-04,83843.804688,84696.148438,81670.750000,83100.250000,45157640207,0.008916,4
2025-04-05,83504.796875,84207.015625,82377.734375,83844.703125,14380803631,-0.004043,5
2025-04-06,78214.484375,83704.718750,77097.742188,83504.507812,36294853736,-0.063353,6
2025-04-07,79235.335938,81119.062500,74436.679688,78221.335938,91262424987,0.013052,0
2025-04-08,76271.953125,80823.890625,76198.023438,79218.476562,48314590749,-0.037400,1

In [57]:
import numpy as np
import ta

In [58]:
btc = btc.sort_index()

In [59]:
# Indicadores técnicos
btc['RSI_5'] = ta.momentum.RSIIndicator(close=btc['Close'], window=5).rsi()
macd = ta.trend.MACD(close=btc['Close'])
btc['MACD'] = macd.macd()
btc['MACD_signal'] = macd.macd_signal()
boll = ta.volatility.BollingerBands(close=btc['Close'])
btc['Bollinger_High'] = boll.bollinger_hband()
btc['Bollinger_Low'] = boll.bollinger_lband()

In [60]:
btc

,Close,High,Low,Open,Volume,daily_return,day_of_week,RSI_5,MACD,MACD_signal,Bollinger_High,Bollinger_Low
Date,,,,,,,,,,,,
2020-12-25,24664.791016,24710.101562,23463.673828,23733.570312,42068395846,0.039132,4,NaN,NaN,NaN,NaN,NaN
2020-12-26,26437.037109,26718.070312,24522.689453,24677.015625,48332647295,0.071853,5,NaN,NaN,NaN,NaN,NaN
2020-12-27,26272.294922,28288.839844,25922.769531,26439.373047,66479895605,-0.006231,6,NaN,NaN,NaN,NaN,NaN
2020-12-28,27084.808594,27389.111328,26207.640625,26280.822266,49056742893,0.030927,0,NaN,NaN,NaN,NaN,NaN
2020-12-29,27362.437500,27370.720703,25987.298828,27081.810547,45265946774,0.010250,1,94.566508,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-04,83843.804688,84696.148438,81670.750000,83100.250000,45157640207,0.008916,4,50.262905,-1005.697605,-1078.724289,88111.070498,80869.898252
2025-04-05,83504.796875,84207.015625,82377.734375,83844.703125,14380803631,-0.004043,5,47.125185,-970.647937,-1057.109018,88081.337512,80992.142175
2025-04-06,78214.484375,83704.718750,77097.742188,83504.507812,36294853736,-0.063353,6,21.249361,-1354.145086,-1116.516232,88735.038569,79752.320806
2025-04-07,79235.335938,81119.062500,74436.679688,78221.335938,91262424987,0.013052,0,30.459576,-1557.738511,-1204.760688,89029.606876,79109.436093
2025-04-08,76271.953125,80823.890625,76198.023438,79218.476562,48314590749,-0.037400,1,21.384505,-1935.892233,-1350.986997,89379.251873,77701.563752

In [61]:
btc.drop("daily_return", axis=1, inplace=True)
btc.drop("High", axis=1, inplace=True)
btc.drop("Low", axis=1, inplace=True)

In [62]:
btc

,Close,Open,Volume,day_of_week,RSI_5,MACD,MACD_signal,Bollinger_High,Bollinger_Low
Date,,,,,,,,,
2020-12-25,24664.791016,23733.570312,42068395846,4,NaN,NaN,NaN,NaN,NaN
2020-12-26,26437.037109,24677.015625,48332647295,5,NaN,NaN,NaN,NaN,NaN
2020-12-27,26272.294922,26439.373047,66479895605,6,NaN,NaN,NaN,NaN,NaN
2020-12-28,27084.808594,26280.822266,49056742893,0,NaN,NaN,NaN,NaN,NaN
2020-12-29,27362.437500,27081.810547,45265946774,1,94.566508,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2025-04-04,83843.804688,83100.250000,45157640207,4,50.262905,-1005.697605,-1078.724289,88111.070498,80869.898252
2025-04-05,83504.796875,83844.703125,14380803631,5,47.125185,-970.647937,-1057.109018,88081.337512,80992.142175
2025-04-06,78214.484375,83504.507812,36294853736,6,21.249361,-1354.145086,-1116.516232,88735.038569,79752.320806
2025-04-07,79235.335938,78221.335938,91262424987,0,30.459576,-1557.738511,-1204.760688,89029.606876,79109.436093
2025-04-08,76271.953125,79218.476562,48314590749,1,21.384505,-1935.892233,-1350.986997,89379.251873,77701.563752

In [63]:
# Precios anteriores
btc['Close_lag1'] = btc['Close'].shift(1)
btc['Open_lag1'] = btc['Open'].shift(1)
btc['Close_lag2'] = btc['Close'].shift(2)

In [64]:
# Indicadores anteriores
btc['RSI_5_lag1'] = btc['RSI_5'].shift(1)
btc['MACD_lag1'] = btc['MACD'].shift(1)

In [65]:
# Retornos y diferencias
btc['daily_return'] = btc['Close'].pct_change()
btc['daily_return_lag1'] = btc['daily_return'].shift(1)
btc['daily_return_lag2'] = btc['daily_return'].shift(2)
btc['diff_pct'] = (btc['Close'] - btc['Open']) / btc['Open']
btc['diff_pct_lag1'] = btc['diff_pct'].shift(1)

In [66]:
# Medias móviles
btc['rolling_mean_5'] = btc['Close'].rolling(window=5).mean()
btc['rolling_mean_10'] = btc['Close'].rolling(window=10).mean()
btc['mean_20'] = btc['Close'].rolling(window=20).mean()

In [67]:
# Desviación estándar (volatilidad)
btc['rolling_std_5'] = btc['Close'].rolling(window=5).std()
btc['std_10'] = btc['Close'].rolling(window=10).std()

In [68]:
# Desviación respecto a la media
btc['close_vs_ma5'] = btc['Close'] - btc['rolling_mean_5']

In [69]:
# Variables temporales
btc['day_of_week'] = btc.index.dayofweek
btc['is_month_end'] = btc.index.is_month_end.astype(int)
btc['is_friday'] = (btc.index.dayofweek == 4).astype(int)

In [70]:
# Volumen
btc['volume_change'] = btc['Volume'].pct_change()
btc['volume_rolling_mean_5'] = btc['Volume'].rolling(window=5).mean()
btc['volume_rolling_std_5'] = btc['Volume'].rolling(window=5).std()

In [71]:
# Target (predicción de subida al día siguiente)
btc['target'] = (btc['Close'].shift(-1) > btc['Close']).astype(int)

In [72]:
btc

,Close,Open,Volume,day_of_week,RSI_5,MACD,MACD_signal,Bollinger_High,Bollinger_Low,Close_lag1,...,mean_20,rolling_std_5,std_10,close_vs_ma5,is_month_end,is_friday,volume_change,volume_rolling_mean_5,volume_rolling_std_5,target
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-25,24664.791016,23733.570312,42068395846,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,1,NaN,NaN,NaN,1
2020-12-26,26437.037109,24677.015625,48332647295,5,NaN,NaN,NaN,NaN,NaN,24664.791016,...,NaN,NaN,NaN,NaN,0,0,0.148906,NaN,NaN,0
2020-12-27,26272.294922,26439.373047,66479895605,6,NaN,NaN,NaN,NaN,NaN,26437.037109,...,NaN,NaN,NaN,NaN,0,0,0.375466,NaN,NaN,1
2020-12-28,27084.808594,26280.822266,49056742893,0,NaN,NaN,NaN,NaN,NaN,26272.294922,...,NaN,NaN,NaN,NaN,0,0,-0.262082,NaN,NaN,1
2020-12-29,27362.437500,27081.810547,45265946774,1,94.566508,NaN,NaN,NaN,NaN,27084.808594,...,NaN,1050.892182,NaN,998.163672,0,0,-0.077274,5.024073e+10,9.490635e+09,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-04,83843.804688,83100.250000,45157640207,4,50.262905,-1005.697605,-1078.724289,88111.070498,80869.898252,83102.828125,...,84490.484375,1114.785718,1824.006571,413.718750,0,1,0.225375,3.735481e+10,8.941064e+09,0
2025-04-05,83504.796875,83844.703125,14380803631,5,47.125185,-970.647937,-1057.109018,88081.337512,80992.142175,83843.804688,...,84536.739844,1002.168181,1526.384966,-116.465625,0,0,-0.681542,3.443012e+10,1.355613e+10,0
2025-04-06,78214.484375,83504.507812,36294853736,6,21.249361,-1354.145086,-1116.516232,88735.038569,79752.320806,83504.796875,...,84243.679688,2301.144002,1860.323474,-4015.840625,0,0,1.523840,3.605396e+10,1.309818e+10,1
2025-04-07,79235.335938,78221.335938,91262424987,0,30.459576,-1557.738511,-1204.760688,89029.606876,79109.436093,78214.484375,...,84069.521484,2644.466149,2081.164481,-2344.914062,0,0,1.514473,4.478957e+10,2.837128e+10,0
2025-04-08,76271.953125,79218.476562,48314590749,1,21.384505,-1935.892233,-1350.986997,89379.251873,77701.563752,79235.335938,...,83540.407812,3335.431223,2814.163511,-3942.121875,0,0,-0.470597,4.708206e+10,2.803062e+10,0

In [73]:
print(f"Antes de dropna: {len(btc)} filas")

Antes de dropna: 1558 filas

In [74]:
# Elimina filas con NaNs generados por cálculos anteriores
btc.dropna(inplace=True)

# Filtra solo hasta el último día de febrero (ajusta si es otro año)
btc = btc[btc.index <= '2024-02-29']

In [75]:
print(f"Después de dropna: {len(btc)} filas")

Después de dropna: 1122 filas

In [76]:
btc

,Close,Open,Volume,day_of_week,RSI_5,MACD,MACD_signal,Bollinger_High,Bollinger_Low,Close_lag1,...,mean_20,rolling_std_5,std_10,close_vs_ma5,is_month_end,is_friday,volume_change,volume_rolling_mean_5,volume_rolling_std_5,target
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-28,33466.097656,30441.041016,76517157706,3,53.023512,139.997778,871.332464,41063.463645,29800.734988,30432.546875,...,35432.099316,1106.375755,1996.829647,1241.244531,0,0,0.222773,6.157805e+10,9.950421e+09,1
2021-01-29,34316.386719,34318.671875,117894572511,4,59.132153,198.026780,736.671327,40185.776363,30030.300005,33466.097656,...,35108.038184,1453.002608,1698.466118,1686.132031,0,1,0.540760,7.542819e+10,2.470409e+10,0
2021-01-30,34269.523438,34295.933594,65141828798,5,58.607115,237.496002,636.836262,39310.845542,30306.728481,34316.386719,...,34808.787012,1607.642973,1437.376934,1258.642578,0,0,-0.447457,7.647715e+10,2.398051e+10,0
2021-01-31,33114.359375,34270.878906,52754542671,6,46.017538,173.562834,544.181576,38795.304267,30298.061553,34269.523438,...,34546.682910,1588.628715,1139.475131,-5.423438,1,0,-0.190159,7.497697e+10,2.543926e+10,1
2021-02-01,33537.175781,33114.578125,61400400660,0,50.848319,155.223765,466.390014,38688.479716,30201.938057,33114.359375,...,34445.208887,529.197638,1162.818874,-203.532813,0,0,0.163888,7.474170e+10,2.558762e+10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-25,51733.238281,51565.214844,15413239245,6,60.533798,2011.481276,2152.020017,55417.722157,44239.575499,51571.101562,...,49828.648828,442.157358,455.422430,297.150000,0,0,0.015761,2.121064e+10,5.973599e+09,1
2024-02-26,54522.402344,51730.539062,34074411896,0,83.191229,2149.034185,2151.422851,55424.432572,45376.638131,51733.238281,...,50400.535352,1475.205711,998.498567,2549.669531,0,0,1.210724,2.230054e+10,7.862909e+09,1
2024-02-27,57085.371094,54519.363281,49756832031,1,89.870718,2436.766487,2208.491578,56053.675194,46024.110353,54522.402344,...,51038.892773,2632.275295,1893.427556,3956.558594,0,0,0.460240,2.716913e+10,1.477278e+10,1
2024-02-28,62504.789062,57071.097656,83239156760,2,95.059687,3066.746602,2380.142583,58371.959498,45426.148315,57085.371094,...,51899.053906,4532.094555,3674.116896,7021.408594,0,0,0.672919,3.953154e+10,2.837107e+10,0
2024-02-29,61198.382812,62499.183594,65496611844,3,82.348307,3421.157344,2588.345535,59861.339542,45341.886630,62504.789062,...,52601.613086,4499.387206,4323.722500,3789.546094,1,0,-0.213151,4.959605e+10,2.642961e+10,1

In [77]:
btc.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1122 entries, 2021-01-28 to 2024-02-29
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Close                  1122 non-null   float64
 1   Open                   1122 non-null   float64
 2   Volume                 1122 non-null   int64
 3   day_of_week            1122 non-null   int32
 4   RSI_5                  1122 non-null   float64
 5   MACD                   1122 non-null   float64
 6   MACD_signal            1122 non-null   float64
 7   Bollinger_High         1122 non-null   float64
 8   Bollinger_Low          1122 non-null   float64
 9   Close_lag1             1122 non-null   float64
 10  Open_lag1              1122 non-null   float64
 11  Close_lag2             1122 non-null   float64
 12  RSI_5_lag1             1122 non-null   float64
 13  MACD_lag1              1122 non-null   float64
 14  daily_return           1122 non-null   float64
 15  daily_return_lag1      1122 non-null   float64
 16  daily_return_lag2      1122 non-null   float64
 17  diff_pct               1122 non-null   float64
 18  diff_pct_lag1          1122 non-null   float64
 19  rolling_mean_5         1122 non-null   float64
 20  rolling_mean_10        1122 non-null   float64
 21  mean_20                1122 non-null   float64
 22  rolling_std_5          1122 non-null   float64
 23  std_10                 1122 non-null   float64
 24  close_vs_ma5           1122 non-null   float64
 25  is_month_end           1122 non-null   int64
 26  is_friday              1122 non-null   int64
 27  volume_change          1122 non-null   float64
 28  volume_rolling_mean_5  1122 non-null   float64
 29  volume_rolling_std_5   1122 non-null   float64
 30  target                 1122 non-null   int64
dtypes: float64(26), int32(1), int64(4)
memory usage: 276.1 KB

In [84]:
btc.to_csv('../../data/processed/btc_golder.csv')

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
# Paso 1: Features y target
X = btc.drop(columns=['target'])
y = btc['target']

In [81]:
# Paso 2: Primero, separar Train (70%) y Temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, shuffle=False
)

In [82]:
# Paso 3: Luego, separar Temp en Validación (15%) y Test (15%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, shuffle=False
)

In [83]:
# Verificamos tamaños
print(f"Train:      {X_train.shape}")
print(f"Validación: {X_val.shape}")
print(f"Test:       {X_test.shape}")

Train:      (785, 30)
Validación: (168, 30)
Test:       (169, 30)